# sub-path redirect
location = __PATH__ {
    return 301 $scheme://$host$request_uri/;
}

location __PATH__/ {
    alias __INSTALL_DIR__/;

    index index.html;

    # Orijinal kaynak koda ve SQLite veritabanına doğrudan erişimi engelle
    location ~* \.(src\.js|db)$ {
        deny all;
        return 404;
    }

    # PHP-FPM geçişi
    location ~ [^/]\.php(/|$) {
        fastcgi_split_path_info ^(.+?\.php)(/.*)$;
        fastcgi_pass unix:/var/run/php/php__PHPVERSION__-fpm-__APP__.sock;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $request_filename;
    }
}

